language: python
python: [2.7, 3.4, 3.5, 3.6]
env:
  global:
  - FIXTURE_PATH=/tmp/schema_fixture/
  matrix:
  - NIRUM_URL=https://github.com/spoqa/nirum/releases/download/0.3.3/nirum-linux-x86_64
  - NIRUM_URL=https://nightly-builds.nirum.org/travis-builds/nirum-linux-x86_64
install:
- pip install tox-travis
- ls -al
- mkdir -p "$HOME/bin"
- curl -v -L -o "$HOME/bin/nirum" "$NIRUM_URL"
- ls -al "$HOME/bin"
- chmod +x "$HOME/bin/nirum"
- ls -al "$HOME/bin"
- nirum --help
script:
- tox -e devruntime
- tox -e buildfixture
- tox
- tox -e docs
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- |
  if git show --format=%B --quiet "${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}" \
     | grep '\[changelog skip\]' > /dev/null; then
    echo "Skip changelog checker..."
  elif [[ "$TRAVIS_TAG" != "" ]]; then
    ! grep -i "to be released" CHANGES.rst
  else
    [[ "$TRAVIS_COMMIT_RANGE" = "" ]] || \
    [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep CHANGES\.rst)" != "" ]]
  fi
